# fundamentals of tensorflow
In this notebook, I will be covering some of the most fundemental concepts of tensors using Tensorflow.

Topics to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

📖 Resources:
I will be following [Daniel](https://www.youtube.com/watch?v=tpCFfeUEGs8&t=116s) in terms of workflow. For further concept enhancements, I will be using ChatGPT4 and [Tensorflow documentation](https://www.tensorflow.org/guide).

## Introduction to Tensors

In [1]:
# import tf
import tensorflow as tf
print(tf.__version__)

2.13.0


There are quite a few ways to create tensors, however, I am using `tf.constant()` to get familier with the basics of tensors. When we create tensor this way, we get to see the: <br>


1.   shape of Tensor
2.   Data Type of elements in Tensor
3.   numpy value (as numpy and tf are quite inter-related)

Altogether its just a learning experience, as tensor becomes larger, it becomes more and more difficult to create tensorsFurther on, we use tf functions to create tensors for us.





In [23]:
# create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [24]:
# dimension of tensor
scalar.ndim

0

In [25]:
# create a vector using tf.constant()
vector = tf.constant([12,12])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 12], dtype=int32)>, 1)

In [26]:
# create a matrix - with more than one dimesions
matrix = tf.constant([[10,7],
                      [7,10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 2)

In [27]:
# create another matrix, with datatype
another_matrix = tf.constant([[10.,7.],
                      [3.,2.],
                      [8.,9.]], dtype=tf.float16) # the higher the no, the more space (being exact) it takes. so float16 will take less space than float32.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [28]:
another_matrix.ndim

2

The dimension is different than shape. So we can say dimension is the no of element in the shape... as if *now*

In [29]:
# create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [30]:
tensor.ndim   # no of elements in a shape

3

What we have created so far:


1.   A **scalar** is a single no
2.   A **vector** is a no with a direction
3. A **Matrix** is a 2D array of no
4. A **Tensor** is an n-dim array of nos. (n can be any int from 0- infinity)



### creatinf tensor through **variable**

In [31]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [32]:
# lets change one of the elements in our changable tensor
changable_tensor[0]                          # first element of tensor
changable_tensor[0] = 70
changable_tensor

TypeError: ignored

In [33]:
changable_tensor[0].assign(7)          # we can use assign to alter the values in tensor
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [34]:
# now unchangable tensor
unchangable_tensor[0]
unchangable_tensor[0].assign(9)

AttributeError: ignored

In Neural Network, sometimes there is a need of Tensors, which can be altered, hence `tf.Variable()`. and sometimes we need tensors that cannot be altered, such as tensor created by `tf.constant()`.

### Creating a Random Tensors
Random Tensors are Tensors with arbitrary size and some Random nos. It is necessary to learn about Random Tensors, b/c Neural Networks begin with (initialize with) Random Tensors as weights, then it agjust the weights according to inputs and models hyperparamentses.

In [35]:
# create 2 random (same) tensors
random_1 = tf.random.Generator.from_seed(42)       # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))             # Tensor with values from Normal distn with the stated shape
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [36]:
random_2 = tf.random.Generator.from_seed(42)       # set seed for reproducibility
random_2 = random_2.normal(shape = (3,2))

# Are random_1 equals random_2?
random_2, random_1, random_2 == random_1         # same b/c we are using same seed

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in the Tensor
One reason for shuffle to avoid the bias that input tensor brings to NN. by shuffling will be a way to give NN more unbiased playground to select the weights

In [37]:
not_shuffle = tf.constant([[10,7],
                           [3,4],
                           [2,5]])

# shuffle
tf.random.shuffle(not_shuffle)    # Randomly shuffle a Tensor along 1st dimension


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [38]:
# shuffle
tf.random.shuffle(not_shuffle)     # different order each time

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [39]:
# shuffle
tf.random.set_seed(42)             # global lever seed
tf.random.shuffle(not_shuffle, seed = 42)    # operational level seed

# Seed based operation derived from first global then operation seed - for reproducible randomness

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

It appears if we want "shuffled" tensors to be in same order, then we must use global and operational level randomm seed.
> [Rule 4](https://www.tensorflow.org/api_docs/python/tf/random/set_seed): If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

It is important to know that, b/c as NN initializes with **Random** patterns of weights, it endsup showing different results everytime for the same experiment. Therefore, to make a reproducible experiments, it is imp to shuffle the data in a same order everytime and initialize with the similar random pattern, and run through the experiment.

### other ways to make Tensors

#### 1s and 0s similar to Numpy

In [40]:
# ones
tf.ones([3,2], float)     # shape and datatype

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [41]:
# zeros
tf.zeros(shape = (3,10))

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

The main diff b/w Numpy array and TF Tensors, is that, tensors can be run on a GPU ( faster for Numericcomputing).

In [2]:
# Numpy Array
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)      # numpy array
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [3]:
# turning numpy array into tensors
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape = (3,8))      # for shape - ensure the shape equates to no of elements in an array (e.g: 24 = 8*3 OR 2*3*4)
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

### Getting Info from Tensors

Tnsor attributes:
* shape - the length of no of elements for each dimension of tensor  `tf.shape`
* Rank - The no of Tensor dimensions `tf.ndim`
* axis or dimensions - specific dimension of a tensor (e.g: index of a 1st dimension `tensor[0]` OR `tensor[:, 1]` suggest all elements of   
* size - total no of items in the tensor `tf.size(tensor)`

In [44]:
# Rank 4 Tensor
rank_4_dim = tf.zeros(shape = [2,3,4,5])     # ndim = 4 (remember it is the no of elements in the shape)!
rank_4_dim, rank_4_dim.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4)

In [45]:
rank_4_dim[0]       # 0th axix

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [46]:
tf.size(rank_4_dim)    # 120 elements = 2*3*4*5

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [47]:
# various attributes of tensor
print("Datatype of every element: ", rank_4_dim.dtype)
print("no of Dimensions (rank): ", rank_4_dim.ndim)
print("Shape of a Tensor: ", rank_4_dim.shape)
print("Elements along 0th axis: ", rank_4_dim.shape[0])
print("Elements along the last axis: ", rank_4_dim.shape[-1])
print("Total no of elements in out Tensors: ", tf.size(rank_4_dim).numpy())

Datatype of every element:  <dtype: 'float32'>
no of Dimensions (rank):  4
Shape of a Tensor:  (2, 3, 4, 5)
Elements along 0th axis:  2
Elements along the last axis:  5
Total no of elements in out Tensors:  120


### Indexing Tensors (similar to Python list)

In [48]:
some_liat = [1,2,3,4]
some_liat[:2]          # 1st 2 elements of a list

[1, 2]

In [49]:
# 1st 2 elements of each dimension
rank_4_dim[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [50]:
# 1st element from each dimension from each index except the last one
rank_4_dim[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [51]:
# create a rank 2 tensor
rank_2_tensor = tf.constant(10, shape = (2,2))
rank_2_tensor, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 10],
        [10, 10]], dtype=int32)>,
 2)

In [52]:
# Last item of each row of a tensor
rank_2_tensor[:, -1]              # [row, column]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

#### Alter the size of a Tensor
it is imp to manipulate the tensor size for customizing NN

In [53]:
# Adding extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]   # this means [every axis b4, tf.newaxis]. we could have write [:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [10]],

       [[10],
        [10]]], dtype=int32)>

### Manipulatinf Tensors (How to manipulate and combine Tensors)
If Data in Tensors, by manipulating Tensors, it is easier to find relevent pattern initially. in addition to python function, we can use Tensorflow functions.


#### Basic Operation (element-wise)
`+`, `-`, `*`, `/`

In [54]:
# adding values via addition
tensor = tf.constant([[10,7],[3,4]])
tensor+10                             # While original remains same.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [55]:
# sub
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [56]:
#
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [57]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

#### TensorFlow Built-in function

In [59]:
tf.multiply(tensor, 10)     # same as tensor*10 - initial tensor unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [60]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

#### Matrix Multiplication

>   Rule1: The inner dimension must match

>   Rule2: The resulting matrix has the shape of outer dimensions

This leads to important observation. To obtain the desired result, it is necessary to keep a check which tensor is being manipulated. As different tensor manipulation (same tensors with different shapes) and later tensor multiplication results in an entirely different result!

In [61]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [62]:
# Tensor multiplication with python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [63]:
# Tensor multiplication with TF
tf.matmul(tensor, tensor)              # same!

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [6]:
A = tf.constant([[1,2],
                 [3,4],
                 [5,6]], float)          # 3x2 matrix
B = tf.constant([[7,8],
                 [9,10],
                 [11,12]], float)        # 3x2 Tensor

# since 3x2 * 3x2 wont multiple - change the shape of B

In [7]:
C = tf.reshape(B, shape=(2,3))

tf.matmul(A,C)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 27.,  30.,  33.],
       [ 61.,  68.,  75.],
       [ 95., 106., 117.]], dtype=float32)>

**Dot Product**
A matrix multiplication can be done:
* `tf.matmul()`
* `tf.tensordot()`

In [8]:
# perform the dot product where A or B needs to be transposed - Goal: check what difference does reshape gives to transpose
tf.tensordot(tf.transpose(A),B, axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 89.,  98.],
       [116., 128.]], dtype=float32)>

In [9]:
# perform matrix multiplication b/w A & B(transposed)
tf.matmul(A, tf.transpose(B))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 23.,  29.,  35.],
       [ 53.,  67.,  81.],
       [ 83., 105., 127.]], dtype=float32)>

In [10]:
# perform matrix multiplication b/w A & B(reshaped)
tf.matmul(A, tf.reshape(B, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 27.,  30.,  33.],
       [ 61.,  68.,  75.],
       [ 95., 106., 117.]], dtype=float32)>

**AxB(transposed)** is different than **AxB(reshaped)**


In [12]:
# checking the values of B-transposed and B-reshaped - to find out the diff
print("B:")
print(B, "\n")

print("B transposed:")
print(tf.transpose(B),"\n")

print("B reshaped to (2,3):")
print(tf.reshape(B, (2,3)),"\n")


B:
tf.Tensor(
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(3, 2), dtype=float32) 

B transposed:
tf.Tensor(
[[ 7.  9. 11.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32) 

B reshaped to (2,3):
tf.Tensor(
[[ 7.  8.  9.]
 [10. 11. 12.]], shape=(2, 3), dtype=float32) 



Generally when performing mmatrix multiplication on Tensors, and axes dont line up, it is imp to **transpose** rather reshape to satisfy the multiplication rule.

### Changing the datatype of Tensor

In [13]:
# tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [16]:
# change from float 32 - float16 (reduce precision to increase the speed)
D = tf.cast(B, dtype = tf.float16)
D, D.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [17]:
# from int32 to float32
C = tf.constant([7,15])
E = tf.cast(C, dtype = tf.float32)

C, E, C.dtype, E.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 15], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 15.], dtype=float32)>,
 tf.int32,
 tf.float32)

### Aggregating Tensors

condensing the tensor from multiple values down to smaller amount values


In [18]:
# get absolute value\
D = tf.constant([-7,-10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Forms of aggregation:
* Get minimum
* maximum
* mean of tensor
* sum of Tensor

In [24]:
random_tensor = tf.constant(np.random.randint(0,100, size=50))
random_tensor, random_tensor.ndim, random_tensor.shape, tf.size(random_tensor)

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([63, 65, 19, 78, 12, 44, 74, 42, 72, 62, 75,  3, 30, 87, 80, 23, 32,
        21, 46, 47,  3, 77, 95, 39,  6, 29, 76,  0, 25, 24, 10, 78, 97, 26,
        74, 98, 54, 10, 54, 45, 19, 48, 41, 15, 21, 48, 95, 81, 60, 10])>,
 1,
 TensorShape([50]),
 <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [25]:
# find muin
tf.reduce_max(random_tensor)


<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [26]:
# find mean
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [27]:
# find max
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [28]:
# find sum
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2333>

In [29]:
# find var - need access to tensor flow prob
import tensorflow_probability as tfp
tfp.stats.variance(random_tensor)


<tf.Tensor: shape=(), dtype=int64, numpy=824>

### Find the positional max & min of Tensor
When get NN prediction probabilities (Representation outputs), this helps to locate the index of values


In [31]:
# creating a Random Tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [34]:
# Find the positional max (argmax)
tf.argmax(F), F[tf.argmax(F)]              # position, value

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [35]:
# Or for value, we can use the prev method
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [36]:
# check if both method return same value:
F[tf.argmax(F)]  == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [37]:
# find the positional min
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a Tensor (removing all single dimensions)

In [3]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,2,1,25) )
G

<tf.Tensor: shape=(1, 1, 2, 1, 25), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],

         [[0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [4]:
G.shape

TensorShape([1, 1, 2, 1, 25])

In [6]:
G_squeeze = tf.squeeze(G)
G_squeeze, G_squeeze.shape         # remove all single dimensions

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
         0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
         0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
        [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
         0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
         0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
         0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
         0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
       dtype=float32)>,
 TensorShape([2, 25]))

### One-hot encoding Tensors
It is a way of Numerical encoding. It is imp to Numerically encode all the input data, as model cannot perform if non-numerics given.

In [8]:
# Create a list of indices
A = [0,1,2,3,4]

# one-hot encode
tf.one_hot(A, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [9]:
# specify custom values for one-hot encoding (fun Ex)
tf.one_hot(A, depth =5, on_value="I love Deep Learning", off_value="I also like to dance")


<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'I love Deep Learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I love Deep Learning',
        b'I also like to dance', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I love Deep Learning', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'I love Deep Learning',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'I also like to dance',
        b'I love Deep Learning']], dtype=object)>

In [11]:
tf.one_hot(A, depth =5, on_value=2.0, off_value=0.5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[2. , 0.5, 0.5, 0.5, 0.5],
       [0.5, 2. , 0.5, 0.5, 0.5],
       [0.5, 0.5, 2. , 0.5, 0.5],
       [0.5, 0.5, 0.5, 2. , 0.5],
       [0.5, 0.5, 0.5, 0.5, 2. ]], dtype=float32)>

### Tensors & Numpy
